version: "3"

services:
  node:
    image: test
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - teste
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    ports:
      - 35432:5432
    networks:
      - teste
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - app-data:/var/lib/postgres/data

  nginx:
    image: nginx
    ports:
      - 80:80
    networks:
      - teste
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  teste:
volumes:
  app-data:
